### ISSUE TITLE
crystal-pg hangs on error when RETURNING is used

### ISSUE THREAD

**Issue by zolamk** [will/crystal-pg#101] opened 2017-06-30 13:41 UTC
i have the following code snippet

    def save

        DB.open(Settings::DB) do | db |

            begin

                id = db.query_one("INSERT INTO users(first_name, last_name, birthdate, sex, username, password, avatar) VALUES($1, $2, $3, $4, $5, $6, $7) RETURNING id;", @first_name, @last_name, @birthdate, @sex, @username, @password, @avatar, as: {Int64})

                @id = id

            rescue ex : PQ::PQError

               puts ex.fields[7].message

            end

        end

    end

when there are no errors the above code runs successfully but if there is a database error like when a unique constraint fails the program just hangs, this happens only when i use `RETURNING`.

**Comment by bigtunacan** [comment] 2017-07-09 17:01
@zolamk Can you confirm you are updated to the last master?  This sounds very much like issue #98 that was recently fixed.

**Comment by imdrasil** [comment] 2017-09-12 18:22
@zolamk This issue still exists but in slightly another manner: when table has unique index on some field and u try to insert duplicate - it will just freeze (described [here](https://github.com/imdrasil/jennifer.cr/issues/35))

**Comment by vladfaust** [comment] 2017-12-24 01:16
I'm bumping this issue because I think it's a critical bug. Literally no ORM in Crystal can safely run `RETURNING` statement for now.

**Comment by pynixwang** [comment] 2017-12-24 09:36
I use `db.scalar`. it works well. 

`db.query_one` return something more and it waits for read and hangs up?

**Comment by vladfaust** [comment] 2017-12-24 11:47
@pynixwang are you sure `RETURNING` works well in this case:

> when table has unique index on some field and u try to insert duplicate - it will just freeze

? Please do some tests and you'll see...

**Comment by pynixwang** [comment] 2017-12-24 12:07
@vladfaust 

`User.exec("CREATE UNIQUE INDEX name_index ON users (name)")`
```
      user = User.new
      user.name = "Test User"
      user.total = 10
      user.save
      user = User.new
      user.name = "Test User"
      user.save
```

`Save Exception: duplicate key value violates unique constraint "name_index"`


no hang up.

**Comment by imdrasil** [comment] 2017-12-24 14:18
@pynixwang which ORM do you use?

**Comment by imdrasil** [comment] 2017-12-24 17:30
Hm, it is interesting - seems that now (somewhy) it works well. It may be caused by some db specific behavior

**Comment by pynixwang** [comment] 2017-12-24 18:28
@bigtunacan this issue opened  on Jun 30, maybe fixed sometime.

**Comment by asterite** [comment] 2019-07-24 19:09
I think this issue can be closed too. I can't reproduce it. This is what I tried:

```crystal
require "pg"

url = "postgres://..."
db = DB.open(url)
db.exec("drop table users")
db.exec("create table users(id int primary key, name text)")
db.exec("alter table users add constraint name_is_unique UNIQUE (name)")
p db.query_one("insert into users (id, name) values (1, 'foo') returning id", as: {Int32})
begin
  p db.query_one("insert into users (id, name) values (2, 'foo') returning id", as: {Int32})
rescue ex
end

p db.query_one("insert into users (id, name) values (3, 'bar') returning id", as: {Int32})
```

**Comment by will** [comment] 2019-07-24 22:51
I'll go ahead and close it per the last few comments saying it doesn't happen any more. If anyone sees it though please reopen.

**Closed by will** 2019-07-24 22:51 UTC
