### ISSUE TITLE
Nullable Text Field Record Causing Exception

### ISSUE THREAD

**Issue by woodzer** [will/crystal-pg#102] opened 2017-07-13 08:14 UTC
If you create a simple table containing a column with a type of ```text``` that accepts null values then you get an exception and stack trace from the following code if there are any records in the table...

```crystal
require "db"
require "pg"
require "./db_issue/*"

module DbIssue
  DB.open("postgres://user_name@localhost/database_name") do |connection|
    connection.query("select * from test_table") do |resultset|
    end
  end
end
```

Obviously you'll need to replace ```user_name``` and ```database_name``` with the appropriate values in this code. The stack trace generated (on OSX) is...

```
Index out of bounds (IndexError)
0x103ca4515: *CallStack::unwind:Array(Pointer(Void)) at ??
0x103ca44b1: *CallStack#initialize:Array(Pointer(Void)) at ??
0x103ca4488: *CallStack::new:CallStack at ??
0x103c936d5: *raise<IndexError>:NoReturn at ??
0x103cc776a: *Slice(UInt8)@Slice(T)#+<Int32>:Slice(UInt8) at ??
0x103d5214d: *Socket+@IO::Buffered#skip<Int32>:Nil at ??
0x103d4c932: *PQ::Connection#skip_bytes<Int32>:Nil at ??
0x103d6c875: *PG::ResultSet#skip:Int32 at ??
0x103d6c2fd: *PG::ResultSet#do_close:Nil at ??
0x103d6c22d: *PG::ResultSet@DB::Disposable#close:(Bool | Nil) at ??
0x103c88c19: __crystal_main at ??
0x103c9d1f8: main at ??
```

This doesn't get generated if the nullable column actually has a value or if the table has no records in it.

**Comment by will** [comment] 2017-08-25 03:47
I was able to figure out that this also will happen with a `DB.mapping` if there are two, but not one, nulls. If there is just one, the crystal-db wrapper appears to notice it.

Also after this happens, it leaves the connection in a bad state and normal queries no longer work

```crystal 
require "pg"
PGDB = DB.open("postgres:///")

struct Foo
  DB.mapping(a: Int32, b: Int32)
end

def capture(title)
  puts "\n\n#{title}"
  begin
    yield
  rescue e
    puts e.message
    p e.backtrace
  end
end

def normal
  capture("normal query") do
    p PGDB.query_all("select 1 as id union select null as id", &.read(Int32?))
  end
end

normal

capture("mapping with no nulls") do
  p Foo.from_rs(PGDB.query("select 1 as a, 1 as b"))
end

normal

capture("mapping with 1 null") do
  p Foo.from_rs(PGDB.query("select 2 as a, null as b"))
end

normal

capture("mapping with 2 nulls") do
  p Foo.from_rs(PGDB.query("select null as a, null as b"))
end

normal
```

```


normal query
[1, nil]


mapping with no nulls
[Foo(@a=1, @b=1)]


normal query
[1, nil]


mapping with 1 null
PG::ResultSet#read returned a Nil. A Int32 was expected.
["0x1060f47a5: *CallStack::unwind:Array(Pointer(Void)) at ??",
 "0x1060f4741: *CallStack#initialize:Array(Pointer(Void)) at ??",
 "0x1060f4718: *CallStack::new:CallStack at ??",
 "0x1060d8115: *raise<Exception>:NoReturn at ??",
 "0x1060d80cd: *raise<String>:NoReturn at ??",
 "0x1061cc745: *PG::ResultSet@DB::ResultSet#read<Int32:Class>:Int32 at ??",
 "0x1061da44f: *Foo#initialize<PG::ResultSet>:Int32 at ??",
 "0x1061da33d: *Foo::new<PG::ResultSet>:Foo at ??",
 "0x1061da2a5: *Foo::from_rs<PG::ResultSet>:Array(Foo) at ??",
 "0x1060d7a17: __crystal_main at ??",
 "0x1060ec248: main at ??"]


normal query
[1, nil]


mapping with 2 nulls
Index out of bounds
["0x1060f47a5: *CallStack::unwind:Array(Pointer(Void)) at ??",
 "0x1060f4741: *CallStack#initialize:Array(Pointer(Void)) at ??",
 "0x1060f4718: *CallStack::new:CallStack at ??",
 "0x1060e2655: *raise<IndexError>:NoReturn at ??",
 "0x1061191ea: *Slice(UInt8)@Slice(T)#+<Int32>:Slice(UInt8) at ??",
 "0x1061aebdd: *Socket+@IO::Buffered#skip<Int32>:Nil at ??",
 "0x1061a915a: *PQ::Connection#skip_bytes<Int32>:Nil at ??",
 "0x1061ca605: *PG::ResultSet#skip:Int32 at ??",
 "0x1061cc3bd: *PG::ResultSet#do_close:Nil at ??",
 "0x1061cc2ed: *PG::ResultSet@DB::Disposable#close:(Bool | Nil) at ??",
 "0x1061da270: *Foo::from_rs<PG::ResultSet>:Array(Foo) at ??",
 "0x1060d7b12: __crystal_main at ??",
 "0x1060ec248: main at ??"]


normal query
Expected PQ::Frame::ParseComplete but got PQ::Frame::CommandComplete(@bytes=Bytes[83, 69, 76, 69, 67, 84, 32, 49, 0])
["0x1060f47a5: *CallStack::unwind:Array(Pointer(Void)) at ??",
 "0x1060f4741: *CallStack#initialize:Array(Pointer(Void)) at ??",
 "0x1060f4718: *CallStack::new:CallStack at ??",
 "0x1060d8115: *raise<Exception>:NoReturn at ??",
 "0x1060d80cd: *raise<String>:NoReturn at ??",
 "0x1061a8f80: *PQ::Connection#expect_frame<PQ::Frame::ParseComplete:Class, Nil>:PQ::Frame::ParseComplete at ??",
 "0x1061a8e7b: *PQ::Connection#expect_frame<PQ::Frame::ParseComplete:Class>:PQ::Frame::ParseComplete at ??",
 "0x10619b6e0: *PG::Statement#perform_query<Tuple()>:PG::ResultSet at ??",
 "0x1061a6295: *DB::Statement+@DB::Statement#perform_query_with_rescue<Tuple()>:PG::ResultSet at ??",
 "0x1061a627a: *DB::Statement+@DB::Statement#query:PG::ResultSet at ??",
 "0x1061c9f0d: *DB::PoolStatement+@DB::PoolStatement#query:PG::ResultSet at ??",
 "0x106187c35: *DB::Database@DB::QueryMethods#query<String>:PG::ResultSet at ??",
 "0x1060f2509: *normal:(Array(Int32 | Nil) | Array(String)) at ??",
 "0x1060d7b39: __crystal_main at ??",
 "0x1060ec248: main at ??"]
```

**Comment by ZeWebDev** [comment] 2017-08-31 20:04
I answered this in https://github.com/crystal-lang/crystal-db/issues/59 but i should post it in here since this is really a crystal-pg issue.


There is a problem with crystal-pg, when it tries to skip over null values

It doesnt skip values of size 1 when it should be -1

You can fix this by changing

```crystal

#lib/pg/src/pg/result_set.cr

private def skip
    col_size = conn.read_i32
    conn.skip_bytes(col_size) if col_size != 1
    @column_index += 1
  rescue IO::Error
    raise DB::ConnectionLost.new(statement.connection)
  end

#to

private def skip
  col_size = conn.read_i32
    conn.skip_bytes(col_size) if col_size != -1    #change this to -1
    @column_index += 1
  rescue IO::Error
    raise DB::ConnectionLost.new(statement.connection)
  end

```

**Comment by will** [comment] 2017-09-01 00:08
Thanks for finding that @ZeWebDev! would you want to make a PR, also with a small spec that shows it fixes the issue to prevent regressions in the future?

**Comment by will** [comment] 2017-09-06 00:20
#107 has been merged to master, @woodzer can you see if this fixes your situation?

**Comment by asterite** [comment] 2019-07-24 19:01
This issue can probably be closed (two years old, plus a fix seems to have been pushed).

(just to make it easier to browse issues and see what else needs fixing)

**Comment by will** [comment] 2019-07-24 19:05
Yeah if #107 doesn't actually fix, please reopen.

**Closed by will** 2019-07-24 19:05 UTC
